export const ERROR_CODES = {
  MISSING_PARAM: 'MISSING_PARAM',
  INVALID_CURRENCY: 'INVALID_CURRENCY',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  UNKNOWN_CURRENCY: 'UNKNOWN_CURRENCY',
  UPSTREAM_FAILURE: 'UPSTREAM_FAILURE',
  UPSTREAM_RATE_LIMIT: 'UPSTREAM_RATE_LIMIT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_FOUND: 'NOT_FOUND',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const HTTP_STATUS = {
  OK: 200,
  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  INTERNAL_SERVER_ERROR: 500,
  BAD_GATEWAY: 502,
} as const;
